version: "3"

services:
  db:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    env_file:
      - ".env"

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - "db"
    ports:
      - 8081:8081
    env_file:
      - ".env"

  tgbot:
    container_name: econothingextrabot
    build:
      context: .
    command: python app.py
    restart: always
    env_file:
      - ".env"

volumes:
  mongodb:
  mongoconfig:
